<?php

namespace AppBundle\Repository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends \Doctrine\ORM\EntityRepository
{

    public function countTicketsReserved(\DateTime $visitDate){

        $date = $visitDate->format("Y-m-d");
        $qb = $this->createQueryBuilder('t');
        $qb->select('sum(t.ticketNumber)');
        $qb->where('t.visitDate = :visitDate');
        $qb->setParameter('visitDate', $date);

        return $qb->getQuery()->getSingleScalarResult();
    }
}


